### PR TITLE
sharing lecture notes (uni: aj2713)

### PR DESCRIPTION
**Pull request by thismlguy**
I'm sorry I wasn't aware of the 5pm deadline. I'm sharing notes for Sid's part of the lecture.

I'll share another pull request with the second half of the lecture.

### CODE REVIEW

**Comment by jhofman** [comment]
Can you check that everything's in the current version, and if not submit an updated pull request?

Thanks.

**Comment by thismlguy** [comment]
I think my second commit got included in the pull request itself. It should
be there.

**Comment by jhofman** [comment]
Great thanks. It looks like the final version, just wanted to double check.

**Comment by thismlguy** [comment]
Great!

**Pull request merged**
