### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by wendywangwwt**
Hi Professor,
Sorry for being late.. just had so much homework in the last week that I forgot to convert the notes into a Latex file.
I tried command line to do a pull request but not sure if it works, so I'm doing it again manually on github website and hope it works.
Please let me know if my note has any problem.
Thank you,
Wendy

### CODE REVIEW

**Comment by jhofman** [comment]
Can you change the subdirectory name to your uni?

**Comment by wendywangwwt** [comment]
hmmm the thing is my uni is ww2440 but my columbia email has an alias (wanting.wang).
Should I change the subdirectory name to wanting.wang or leave it as it is?

**Comment by jhofman** [comment]
You can change it to ww2440. It doesn't have to match your email.

**Comment by wendywangwwt** [comment]
it's ww2440 in my repo.. what's the name of the subdir you see?

**Comment by jhofman** [comment]
got it---thanks.

**Comment by jhofman** [comment]
(unfortunately template.tex doesn't compile. please fix this!)

**Pull request merged**
