### PR TITLE
sh3266 added scribed notes

### PR DESCRIPTION
**Pull request by restocle**
sh3266 - created scribed lecture notes for Lecture 2 "Introduction to Counting"
This is under Lecture 1 folder because it is the only folder available, but the note taking initiative began from Lecture 2.

### CODE REVIEW

**Comment by jhofman** [comment]
Please add the source .tex files that generated the pdf to the repository as well. Also, I'd recommend writing a bit more for the notes---one page comes in quite short.

**Comment by restocle** [comment]
I will update the doc to include more information and send pull request again. May I know what the expectations and criteria may be for the scribed notes? I wrote down most of verbally communicated information that I thought was important. Should I summarize the lecture note material as well?

**Comment by jhofman** [comment]
Yes, it would be good to capture more details about the various group-by implementations as well as motivation for the long tail question and the associated calculations.

**Comment by restocle** [comment]
I have just committed and pushed. Do I need to create a pull request only once?

**Comment by jhofman** [comment]
You don't need to re-open the request. I'll accept it, and fix a few things:

  1. Your notes should be under the lecture_2 directory.
  2. You shouldn't commit a zip file or any pdfs, but instead the source .tex files from which everything can be built.
  3. The `uni.tex` file should have been renamed to your uni.

Please `pull upstream` to grab these changes from this copy of the repo.

**Comment by restocle** [comment]
Thank you! I apologize for the mistakes. I thought the entire zip would be needed for pictures and other things. Please let me know if anything else is missing!

**Pull request merged**
